title = "Planet of the Crabs"
description = "🦀 fearless rust"
theme = "lightspeed"
base_url = "https://kitallis.github.io/hades/"
compile_sass = true
build_search_index = true
generate_feed = true

[markdown]
highlight_code = true

[extra]
